version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.api
    ports:
      - "8080:8080"
  
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autostonks
  