name: PyTest

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --system --dev
      - name: Test with pytest
        run: |
          export NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}
          pytest
